**1. How to import pandas and check the version?**

In [1]:
import pandas as pd
print(pd.__version__)

2.0.3


**2. How to create a series from a list, numpy array and dict?**

Create a pandas series from each of the items below: a list, numpy and a dictionary

*Input:*

In [2]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [ ]:
s1 = pd.Series(mylist)
s2 = pd.Series(myarr)
s3 = pd.Series(mydict)

s3.head()

a    0
b    1
c    2
e    3
d    4
dtype: int64

**3. How to convert the index of a series into a column of a dataframe?**

Convert the series ser into a dataframe with its index as another column on the dataframe.

*Input:*

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [ ]:
df = ser.to_frame().reset_index()
df.head()

index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4

**4. How to combine many series to form a dataframe?**

Combine ser1 and ser2 to form a dataframe.

*Input:*

In [ ]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [ ]:
df1 = pd.concat([ser1, ser2], axis=1)
print(df1.head())

df2 = pd.DataFrame({'first': ser1, 'second': ser2})
print(df2.head())

   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4
  first  second
0     a       0
1     b       1
2     c       2
3     e       3
4     d       4


**5. How to assign name to the series’ index?**

Give a name to the series ser calling it ‘alphabets’.

*Input:*

In [ ]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [ ]:
ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

**6. How to get the items of series A not present in series B?**

From ser1 remove items present in ser2

*Input:*

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [ ]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

**7. How to get the items not common to both series A and series B?**

Get all items of ser1 and ser2 not common to both.

*Input:*

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [ ]:
s_union = pd.Series(np.union1d(ser1, ser2))
s_intersect = pd.Series(np.intersect1d(ser1, ser2))
s_res = s_union[~s_union.isin(s_intersect)]
s_res.head(10)

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

**8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?**

Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

*Input:*

In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [ ]:
print(ser)
np.percentile(ser, q=[0, 25, 50, 75, 100])

0      7.123397
1      7.115134
2     10.231415
3      6.212276
4      4.422885
5      8.609274
6     16.257148
7      6.792449
8      6.411455
9      3.374795
10    12.988857
11    17.324051
12     8.764687
13    11.452323
14    14.181417
15    10.674779
16    13.314606
17     4.057307
18    11.808527
19    15.698816
20     6.666157
21    11.675914
22    10.695028
23    13.370455
24    21.396792
dtype: float64


array([ 3.37479455,  6.79244882, 10.67477892, 13.31460635, 21.39679188])

**9. How to get frequency counts of unique items of a series?**

Calculte the frequency counts of each unique value ser.

*Input:*

In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [ ]:
print(ser)
ser.value_counts()

0     g
1     h
2     e
3     d
4     b
5     g
6     a
7     e
8     g
9     a
10    c
11    b
12    b
13    f
14    h
15    b
16    a
17    d
18    a
19    d
20    a
21    e
22    a
23    e
24    c
25    d
26    a
27    c
28    c
29    c
dtype: object


a    7
c    5
e    4
d    4
b    4
g    3
h    2
f    1
Name: count, dtype: int64

**10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?**

From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.

*Input:*

In [ ]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [ ]:
print(ser)
print(ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
print(ser)
ser.value_counts()

0     4
1     2
2     2
3     1
4     4
5     2
6     1
7     3
8     4
9     1
10    3
11    1
dtype: int64
1    4
4    3
2    3
3    2
Name: count, dtype: int64
0         4
1     Other
2     Other
3         1
4         4
5     Other
6         1
7     Other
8         4
9         1
10    Other
11        1
dtype: object


Other    5
1        4
4        3
Name: count, dtype: int64

**11. How to bin a numeric series to 10 groups of equal size?**

Bin the series ser into 10 equal deciles and replace the values with the bin name.

*Input:*

In [ ]:
ser = pd.Series(np.random.random(20))

*Desired Output:*

In [ ]:
# First 5 items
0    7th
1    9th
2    7th
3    3rd
4    8th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [ ]:
print(ser)
pd.qcut(ser, q=[0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1], labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])

0     0.113377
1     0.344242
2     0.541883
3     0.503975
4     0.314538
5     0.077642
6     0.485916
7     0.432122
8     0.214188
9     0.877669
10    0.030282
11    0.605431
12    0.893474
13    0.981973
14    0.847821
15    0.245178
16    0.139636
17    0.469525
18    0.728063
19    0.682895
dtype: float64


0      2nd
1      4th
2      7th
3      6th
4      4th
5      1st
6      6th
7      5th
8      3rd
9      9th
10     1st
11     7th
12    10th
13    10th
14     9th
15     3rd
16     2nd
17     5th
18     8th
19     8th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

**12. How to convert a numpy array to a dataframe of given shape?**

Reshape the series ser into a dataframe with 7 rows and 5 columns

*Input:*

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [ ]:
print(ser)
df = pd.DataFrame(ser.values.reshape(7,5))
df

0     9
1     2
2     7
3     3
4     1
5     3
6     1
7     6
8     5
9     4
10    2
11    5
12    8
13    2
14    2
15    6
16    6
17    7
18    8
19    2
20    4
21    6
22    3
23    7
24    1
25    8
26    9
27    8
28    8
29    2
30    7
31    3
32    8
33    6
34    9
dtype: int64


0  1  2  3  4
0  9  2  7  3  1
1  3  1  6  5  4
2  2  5  8  2  2
3  6  6  7  8  2
4  4  6  3  7  1
5  8  9  8  8  2
6  7  3  8  6  9

**13. How to find the positions of numbers that are multiples of 3 from a series?**

Find the positions of numbers that are multiples of 3 from ser.

*Input:*

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))

In [ ]:
print(ser)
np.argwhere(ser % 3 == 0)

0    3
1    3
2    7
3    9
4    3
5    2
6    5
dtype: int64


array([[0],
       [1],
       [3],
       [4]])

**14. How to extract items at given positions from a series**

From ser, extract the items at positions in list pos.

*Input:*

In [ ]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [ ]:
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

**15. How to stack two series vertically and horizontally ?**

Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

*Input:*

In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [ ]:
# Vertical
# print(ser1.append(ser2)) -> For older version of pandas
df_v = pd.concat([ser1, ser2], axis=0)
print(df_v)

# Horizontal
df_h = pd.concat([ser1, ser2], axis=1)
print(df_h)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


**16. How to get the positions of items of series A in another series B?**

Get the positions of items of ser2 in ser1 as a list.

*Input:*

In [ ]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [ ]:
print(ser1[ser1.isin(ser2)].index)

# OR
print([np.where(i == ser1)[0].tolist()[0] for i in ser2])

# OR
print([pd.Index(ser1).get_loc(i) for i in ser2])

Index([0, 4, 5, 8], dtype='int64')
[5, 4, 0, 8]
[5, 4, 0, 8]


**17. How to compute the mean squared error on a truth and predicted series?**

Compute the mean squared error of truth and pred series.

*Input:*

In [ ]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [ ]:
mse = np.mean((pred - truth) ** 2)
print(truth)
print(pred)
print(mse)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0.406805
1    1.227627
2    2.249668
3    3.527044
4    4.206626
5    5.265844
6    6.071037
7    7.836670
8    8.006378
9    9.011817
dtype: float64
0.1376024296709831


**18. How to convert the first character of each element in a series to uppercase?**

Change the first character of each word to upper case in each word of ser.

*Input:*

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [ ]:
ser1 = pd.Series([i.title() for i in ser])

# OR
ser2 = ser.map(lambda x: x.title())

# OR
ser3 = ser.map(lambda x: x[0].upper() + x[1:])

print(ser1)
print(ser2)
print(ser3)

0     How
1      To
2    Kick
3    Ass?
dtype: object
0     How
1      To
2    Kick
3    Ass?
dtype: object
0     How
1      To
2    Kick
3    Ass?
dtype: object


**19. How to calculate the number of characters in each word in a series?**

*Input:*

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [ ]:
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

**20. How to compute difference of differences between consequtive numbers of a series?**

Difference of differences between the consequtive numbers of ser.

*Input:*

In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

*Desired Output:*

In [ ]:
[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

In [ ]:
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


**21. How to convert a series of date-strings to a timeseries?**

*Input:*

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

*Desired Output:*

In [ ]:
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [ ]:
pd.to_datetime(ser, format='mixed')

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

**22. How to get the day of month, week number, day of year and day of week from a series of date strings?**

Get the day of month, week number, day of year and day of week from ser.

*Input:*

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

*Desired output:*

In [ ]:
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

In [ ]:
from dateutil.parser import parse

ser_new = ser.map(lambda x: parse(x))

print("Date: ", ser_new.dt.day.tolist())
print("Week number: ", ser_new.dt.isocalendar().week.tolist())
print("Day num of year: ", ser_new.dt.dayofyear.tolist())
print("Day of week: ", ser_new.dt.day_name().tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


**23. How to convert year-month string to dates corresponding to the 4th day of the month?**

ser to dates that start with 4th of the respective months.

*Input:*

In [ ]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

*Desired Output:*

In [ ]:
0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [ ]:
from dateutil.parser import parse

ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

**24. How to filter words that contain atleast 2 vowels from a series?**

From ser, extract words that contain atleast 2 vowels.

*Input:*

In [ ]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

*Desired Output:*

In [ ]:
0     Apple
1    Orange
4     Money
dtype: object

In [ ]:
from collections import Counter

words = ser.map(lambda x: sum([Counter(x).get(i,0) for i in list('aeiouAEIOU')]) >= 2)
ser[words]

0     Apple
1    Orange
4     Money
dtype: object

**25. How to filter valid emails from a series?**

Extract the valid emails from the series emails. The regex pattern for valid emails is provided as reference.

*Input:*

In [ ]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

*Desired Output:*

In [ ]:
1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [ ]:
import re

result = emails.map(lambda x: bool(re.match(pattern, x)))
print(emails[result]) # -> series of string

# OR
print(emails.str.findall(pattern)) # -> series of list

# OR
print([x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]) # -> just list

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object
0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object
['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']


**26. How to get the mean of a series grouped by another series?**

Compute the mean of weights of each fruit.

*Input:*

In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['apple', 'apple', 'banana', 'carrot', 'apple', 'banana', 'banana', 'apple', 'apple', 'apple']


*Desired output:*

In [ ]:
# values can change due to randomness
apple     6.0
banana    4.0
carrot    5.8
dtype: float64

# my output should be:
apple     1.0 + 2.0 + 5.0 + 8.0 + 9.0 + 10.0 / 6 = 5.833333
banana    3.0 + 6.0 + 7.0 / 3 = 5.333333
carrot    4.0 / 1 = 4.000000

In [ ]:
weights.groupby(fruit).mean()

apple     5.833333
banana    5.333333
carrot    4.000000
dtype: float64

**27. How to compute the euclidean distance between two series?**

Compute the euclidean distance between series (points) p and q, without using a packaged formula.

*Input:*

In [ ]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

*Desired Output:*

In [ ]:
18.165

In [ ]:
sum((p - q) ** 2) ** (1/2)

18.16590212458495

**28. How to find all the local maxima (or peaks) in a numeric series?**

Get the positions of peaks (values surrounded by smaller values on both sides) in ser.

*Input:*

In [ ]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

*Desired output:*

In [ ]:
array([1, 5, 7])

In [ ]:
print(np.diff(ser))
print(np.sign(np.diff(ser)))

dd = np.diff(np.sign(np.diff(ser)))
print(dd)

peak_locs = np.where(dd == -2)[0] + 1
peak_locs

[ 8 -7  1  5  1 -8  5 -4]
[ 1 -1  1  1  1 -1  1 -1]
[-2  2  0  0 -2  2 -2]


array([1, 5, 7])

**29. How to replace missing spaces in a string with the least frequent character?**

Replace the spaces in my_str with the least frequent character.

*Input:*

In [ ]:
my_str = 'dbc deb abed gade'

*Desired Output:*

In [ ]:
'dbccdebcabedcgade'  # least frequent is 'c'

In [ ]:
ser = pd.Series(list(my_str))
least_freq = ser.value_counts().dropna().index[-1]  # 'g' is at the end of the series, so it is the least frequent
new_str = "".join(ser.replace(' ', least_freq))
new_str

'dbcgdebgabedggade'

**30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?**

*Desired output:*

In [ ]:
# values can be random
2000-01-01    4
2000-01-08    1
2000-01-15    8
2000-01-22    4
2000-01-29    4
2000-02-05    2
2000-02-12    4
2000-02-19    9
2000-02-26    6
2000-03-04    6

In [ ]:
data = np.random.randint(1,10,10)
index = pd.date_range('2000-01-01', periods=10, freq='W-SAT')
ser = pd.Series(data, index)
ser

2000-01-01    7
2000-01-08    8
2000-01-15    5
2000-01-22    8
2000-01-29    8
2000-02-05    7
2000-02-12    1
2000-02-19    3
2000-02-26    4
2000-03-04    9
Freq: W-SAT, dtype: int64

**31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?**

ser has missing dates and values. Make all missing dates appear and fill up with value from previous date.

*Input:*

In [ ]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
#> 2000-01-01     1.0
#> 2000-01-03    10.0
#> 2000-01-06     3.0
#> 2000-01-08     NaN
#> dtype: float64

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


*Desired Output:*

In [ ]:
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN

In [ ]:
ser.resample('D').ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

**32. How to compute the autocorrelations of a numeric series?**

Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.

*Input:*

In [ ]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

*Desired output:*

In [ ]:
# values will change due to randomness
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
Lag having highest correlation:  9

In [ ]:
autocorrelations = [ser.autocorr(i) for i in range(11)]
print(autocorrelations[1:])
print("Lag having highest correlation: ", np.argmax(np.abs(autocorrelations[1:])) + 1)

[-0.11311345034658529, 0.256667142987412, -0.09804183143535891, -0.36432930540428843, -0.0714411229487153, -0.44053358535034554, 0.114160641858654, 0.12541583191324976, 0.44268909905133136, 0.3285234369966978]
Lag having highest correlation:  9


**33. How to import only every nth row from a csv file to create a dataframe?**

Import every 50th row of BostonHousing dataset as a dataframe.

*Link:* https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv

In [ ]:
df_all = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv", chunksize=50)
df_50 = pd.concat([chunk.iloc[0] for chunk in df_all], axis=1)
df_50.T

crim    zn  indus  chas    nox     rm    age     dis   rad    tax  \
0     0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900   1.0  296.0   
50    0.08873  21.0   5.64   0.0  0.439  5.963   45.7  6.8147   4.0  243.0   
100   0.14866   0.0   8.56   0.0  0.520  6.727   79.9  2.7778   5.0  384.0   
150   1.65660   0.0  19.58   0.0  0.871  6.122   97.3  1.6180   5.0  403.0   
200   0.01778  95.0   1.47   0.0  0.403  7.135   13.9  7.6534   3.0  402.0   
250   0.14030  22.0   5.86   0.0  0.431  6.487   13.0  7.3967   7.0  330.0   
300   0.04417  70.0   2.24   0.0  0.400  6.871   47.4  7.8278   5.0  358.0   
350   0.06211  40.0   1.25   0.0  0.429  6.490   44.4  8.7921   1.0  335.0   
400  25.04610   0.0  18.10   0.0  0.693  5.987  100.0  1.5888  24.0  666.0   
450   6.71772   0.0  18.10   0.0  0.713  6.749   92.6  2.3236  24.0  666.0   
500   0.22438   0.0   9.69   0.0  0.585  6.027   79.7  2.4982   6.0  391.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  
250     19.1  396.28   5.90  24.4  
300     14.8  390.86   6.07  24.8  
350     19.7  396.90   5.98  22.9  
400     20.2  396.90  26.77   5.6  
450     20.2    0.32  17.44  13.4  
500     19.2  396.90  14.33  16.8

**34. How to change column values when importing csv to a dataframe?**

Import the boston housing dataset, but while importing change the 'medv' (median house value) column so that values < 25 becomes ‘Low’ and > 25 becomes ‘High’.

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv", converters={'medv': lambda x: 'Low' if float(x) < 25 else 'High'})
df.head(10)

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222     18.7   
5  0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222     18.7   
6  0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311     15.2   
7  0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311     15.2   
8  0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311     15.2   
9  0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311     15.2   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High  
5  394.12   5.21  High  
6  395.60  12.43   Low  
7  396.90  19.15  High  
8  386.63  29.93   Low  
9  386.71  17.10   Low

**35. How to create a dataframe with rows as strides from a given series?**

*Input:*

In [ ]:
L = pd.Series(range(15))

*Desired Output:*

In [ ]:
array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [ ]:
def gen_strides(a, stride_len, window_len):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

print(gen_strides(L, stride_len=2, window_len=4))
print(gen_strides(L, stride_len=6, window_len=1))
print(gen_strides(L, stride_len=5, window_len=5))
print(gen_strides(L, stride_len=1, window_len=15))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
[[ 0]
 [ 6]
 [12]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


**36. How to import only specified columns from a csv file?**

Import ‘crim’ and ‘medv’ columns of the BostonHousing dataset as a dataframe.

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv", usecols=['crim', 'medv'])
df

crim  medv
0    0.00632  24.0
1    0.02731  21.6
2    0.02729  34.7
3    0.03237  33.4
4    0.06905  36.2
..       ...   ...
501  0.06263  22.4
502  0.04527  20.6
503  0.06076  23.9
504  0.10959  22.0
505  0.04741  11.9

[506 rows x 2 columns]

**37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.**

Get the number of rows, columns, datatype and summary statistics of each column of the Cars93 dataset. Also get the numpy array and list equivalent of the dataframe.

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv")
print("---------------INFO---------------")
print(df.info())
print("---------------SHAPE---------------")
print(df.shape)
print("---------------DTYPES---------------")
print(df.dtypes)
print("---------------DTYPE COUNTS---------------")
print(df.dtypes.value_counts())
print("---------------STATS---------------")
print(df.describe())
print("---------------ARRAY---------------")
print(df.values)
print("---------------LIST---------------")
print(df.values.tolist())

---------------INFO---------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             55 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 n

**38. How to extract the row and column number of a particular cell with given criterion?**

*Input:*

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

Which manufacturer, model and type has the highest Price? What is the row and column number of the cell with the highest Price value?

In [ ]:
print(df.loc[(df.Price == max(df.Price)), ['Manufacturer', 'Model', 'Type']])

row, col = np.where(df.values == df.Price.max())
print(row, col)

# print(df.iloc[row[0], col[0]]) ---> Price = 61.9

     Manufacturer Model     Type
58  Mercedes-Benz  300E  Midsize
[58] [4]
61.9


**39. How to rename a specific columns in a dataframe?**

Rename the column Type as CarType in df and replace the ‘.’ in column names with ‘_’.

*Input:*

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)
#> Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
#>        'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
#>        'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


*Desired Solution:*

In [ ]:
print(df.columns)
#> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
#>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
#>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')

In [ ]:
df = df.rename(columns={'Type': 'CarType'})

df.columns = df.columns.map(lambda x: x.replace('.', '_'))

df.columns

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

**40. How to check if a dataframe has any missing values?**

Check if df has any missing values.

*Input:*

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
print(df.isnull())
print("--------------------O--------------------")
print(df.isnull().values)
print("--------------------O--------------------")
print(df.isnull().values.any())

    Manufacturer  Model   Type  Min.Price  Price  Max.Price  MPG.city  \
0          False  False  False      False  False      False     False   
1           True  False  False      False  False      False     False   
2          False  False  False      False  False      False     False   
3          False  False  False       True  False      False     False   
4          False  False  False       True  False       True     False   
..           ...    ...    ...        ...    ...        ...       ...   
88         False  False  False      False  False      False     False   
89         False  False  False      False  False      False     False   
90         False  False  False      False  False      False     False   
91         False  False  False      False  False      False     False   
92          True  False  False      False  False      False     False   

    MPG.highway  AirBags  DriveTrain  ...  Passengers  Length  Wheelbase  \
0         False     True       False  ...      

**41. How to count the number of missing values in each column?**

Count the number of missing values in each column of df. Which column has the maximum number of missing values?

*Input:*

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
print(df.isnull().sum())
print("---------------MAX---------------")
print(df.isnull().sum().idxmax())

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64
---------------MAX---------------
AirBags


**42. How to replace missing values of multiple numeric columns with the mean?**

Replace missing values in Min.Price and Max.Price columns with their respective mean.

*Input:*

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
print(df[['Min.Price', 'Max.Price']].head())
print("---------------NEW---------------")

df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'].fillna(df['Max.Price'].mean())

# OR
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))

df[['Min.Price', 'Max.Price']].head()


   Min.Price  Max.Price
0       12.9       18.8
1       29.2       38.7
2       25.9       32.3
3        NaN       44.6
4        NaN        NaN
---------------NEW---------------


Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

**43. How to use apply function on existing columns with global variables as additional arguments?**

In df, use apply method to replace the missing values in Min.Price with the column’s mean and those in Max.Price with the column’s median.

*Input:*

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
df[['Min.Price', 'Max.Price']].head()

Min.Price  Max.Price
0  12.900000      18.80
1  29.200000      38.70
2  25.900000      32.30
3  17.118605      44.60
4  17.118605      19.15

**44. How to select a specific column from a dataframe as a dataframe instead of a series?**

Get the first column (a) in df as a dataframe (rather than as a Series).

*Input:*

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [ ]:
df_new = df['a'].to_frame()
print(type(df_new))

# OR
df_new = df[['a']]
print(type(df_new))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


**45. How to change the order of columns of a dataframe?**

Actually 3 questions.
1. In df, interchange columns 'a' and 'c'.
2. Create a generic function to interchange two columns, without hardcoding column names.
3. Sort the columns in reverse alphabetical order, that is colume 'e' first through column 'a' last.
*Input:*

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [ ]:
# 1
df1 = df[list('cbade')]
print(df1.columns)

# 2
def switch_columns(df, col1, col2):
  colnames = df.columns.tolist()
  c1, c2 = colnames.index(col1), colnames.index(col2)
  colnames[c2], colnames[c1] = colnames[c1], colnames[c2]
  return df[colnames]

df2 = switch_columns(df, 'a', 'c')
print(df2.columns)

# 3
df3 = df[sorted(df.columns, reverse=True)]
print(df3.columns)

# OR
df4 = df.sort_index(axis=1, ascending=False)
print(df4.columns)

Index(['c', 'b', 'a', 'd', 'e'], dtype='object')
Index(['c', 'b', 'a', 'd', 'e'], dtype='object')
Index(['e', 'd', 'c', 'b', 'a'], dtype='object')
Index(['e', 'd', 'c', 'b', 'a'], dtype='object')


**46. How to set the number of rows and columns displayed in the output?**

Change the pandas display settings on printing the dataframe df it shows a maximum of 10 rows and 10 columns.

*Input:*

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [ ]:
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

**47. How to format or suppress scientific notations in a pandas dataframe?**

Suppress scientific notations like ‘e-03’ in df and print upto 4 numbers after decimal.

*Input:*

In [3]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df
#>          random
#> 0  3.474280e-03
#> 1  3.951517e-05
#> 2  7.469702e-02
#> 3  5.541282e-28

random
0  0.010060
1  0.012015
2  0.122379
3  0.153578

*Desired Output:*

In [ ]:
#>    random
#> 0  0.0035
#> 1  0.0000
#> 2  0.0747
#> 3  0.0000

In [10]:
df_round_1 = df.round(4)
print(df_round_1)

# OR
df_round_2 = df.apply(lambda x: '%.4f' % x.iloc[0], axis=1)
print(df_round_2)

# OTHER SOLUTIONS
print("---------------#1---------------")
print(df.applymap(lambda x: '%.4f' % x))

print("---------------#2---------------")
pd.set_option('display.float_format', lambda x: '%.4f' % x)
print(df)

print("---------------#3---------------")
pd.options.display.float_format = None
pd.options.display.float_format = '{:.4f}'.format
print(df)

print("---------------#Reset---------------")
pd.options.display.float_format = None
print(df)

   random
0  0.0101
1  0.0120
2  0.1224
3  0.1536
0    0.0101
1    0.0120
2    0.1224
3    0.1536
dtype: object
---------------#1---------------
   random
0  0.0101
1  0.0120
2  0.1224
3  0.1536
---------------#2---------------
   random
0  0.0101
1  0.0120
2  0.1224
3  0.1536
---------------#3---------------
   random
0  0.0101
1  0.0120
2  0.1224
3  0.1536
---------------#Reset---------------
     random
0  0.010060
1  0.012015
2  0.122379
3  0.153578


**48. How to format all the values in a dataframe as percentages?**

Format the values in column 'random' of df as percentages.

*Input:*

In [11]:
df = pd.DataFrame(np.random.random(4), columns=['random'])
df
#>      random
#> 0    .689723
#> 1    .957224
#> 2    .159157
#> 3    .21082

random
0  0.469824
1  0.802805
2  0.753955
3  0.975467

*Desired Output:*

In [ ]:
#>      random
#> 0    68.97%
#> 1    95.72%
#> 2    15.91%
#> 3    2.10%

In [12]:
df_perc = df.style.format({'random': '{0:.2%}'.format})
df_perc

**49. How to filter every nth row in a dataframe?**

From df, filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

*Input:*

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [14]:
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


**50. How to create a primary key index by combining relevant columns?**

In df, Replace NaNs with ‘missing’ in columns 'Manufacturer', 'Model' and 'Type' and create a index as a combination of these three columns and check if the index is a primary key.

*Input:*

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

*Desired Output:*

In [ ]:
                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN

In [20]:
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna("missing")
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.head())
print("---------------Is Index a Primary Key?---------------")
print(df.index.is_unique)

                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN
---------------Is Index a Primary Key?---------------
True


**51. How to get the row number of the nth largest value in a column?**

Find the row position of the 5th largest value of column 'a' in df.

*Input:*

In [21]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

In [44]:
print(df.sort_values(by='a', ascending=False).iloc[4].name)

# OR
print(df['a'].argsort()[::-1][5])

8
8


**52. How to find the position of the nth largest value greater than a given value?**

In ser, find the position of the 2nd largest value greater than the mean.

*Input:*

In [45]:
ser = pd.Series(np.random.randint(1, 100, 15))

In [51]:
print(np.argwhere(ser > ser.mean())[1])

[3]


**53. How to get the last n rows of a dataframe with row sum > 100?**

Get the last two rows of df whose row sum is greater than 100.

*Input:*

In [52]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [66]:
df_new = df.iloc[np.where(df.apply(np.sum, axis=1) > 100)[0][-2:], :]
df_new

0   1   2   3
13  30  31  24  37
14  34  19  35  16

**54. How to find and cap outliers from a series or dataframe column?**

Replace all values of ser in the lower 5%ile and greater than 95%ile with respective 5th and 95th %ile value.

*Input:*

In [67]:
ser = pd.Series(np.logspace(-2, 2, 30))

In [77]:
low, high = ser.quantile([.05, .95])
ser[ser < low] = low
ser[ser > high] = high
print(f'5th percentile= {low} | 95th percentile= {high}')
print("---------------o---------------")
print(ser)

5th percentile= 0.018830915148138196 | 95th percentile= 53.14901559316227
---------------o---------------
0      0.018831
1      0.018831
2      0.018874
3      0.025929
4      0.035622
5      0.048939
6      0.067234
7      0.092367
8      0.126896
9      0.174333
10     0.239503
11     0.329034
12     0.452035
13     0.621017
14     0.853168
15     1.172102
16     1.610262
17     2.212216
18     3.039195
19     4.175319
20     5.736153
21     7.880463
22    10.826367
23    14.873521
24    20.433597
25    28.072162
26    38.566204
27    52.983169
28    53.149016
29    53.149016
dtype: float64


**55. How to reshape a dataframe to the largest possible square after removing the negative values?**

Reshape df to the largest possible square with negative values removed. Drop the smallest values if need be. The order of the positive numbers in the result should remain the same as the original.

*Input:*

In [101]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

In [111]:
print(df)
df = df[df > 0]
arr = df.values.flatten()
arr_new = arr[~np.isnan(arr)]
side_length = int(arr_new.shape[0]**.5)
excess = arr_new.shape[0] - side_length**2
sorted_arr = np.sort(arr_new)
result_arr = arr_new[:arr_new.shape[0]-excess]
df_new = pd.DataFrame(result_arr.reshape(side_length,-1))
df_new

# SOLUTION OF machinelearningplus.com
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

      0     1     2     3     4     5     6     7     8     9
0  31.0  43.0  12.0  35.0  10.0   NaN  36.0   NaN   NaN  47.0
1   7.0   NaN   4.0  14.0   NaN  31.0  37.0  36.0   8.0  12.0
2  37.0   NaN   NaN  22.0  46.0   NaN  17.0   NaN  48.0   NaN
3   NaN  34.0  29.0  12.0  11.0  25.0   3.0   NaN   3.0  31.0
4  16.0  23.0   NaN  27.0  12.0  13.0  27.0   NaN  43.0  42.0
5   NaN   NaN   NaN   2.0   1.0   NaN  42.0   2.0  25.0   NaN
6   NaN  23.0   1.0   NaN   NaN  45.0   NaN   NaN  38.0   NaN
7   NaN   NaN  19.0  31.0  32.0  21.0  39.0   NaN  40.0  38.0
8   NaN  15.0  42.0  44.0   NaN  14.0  13.0   8.0   3.0  31.0
9   6.0   NaN  31.0  32.0   NaN   NaN   1.0  23.0  38.0  37.0


0     1     2     3     4     5     6     7
0  31.0  43.0  12.0  35.0  10.0  36.0  47.0   7.0
1   4.0  14.0  31.0  37.0  36.0   8.0  12.0  37.0
2  22.0  46.0  17.0  48.0  34.0  29.0  12.0  11.0
3  25.0   3.0   3.0  31.0  16.0  23.0  27.0  12.0
4  13.0  27.0  43.0  42.0   2.0   1.0  42.0   2.0
5  25.0  23.0   1.0  45.0  38.0  19.0  31.0  32.0
6  21.0  39.0  40.0  38.0  15.0  42.0  44.0  14.0
7  13.0   8.0   3.0  31.0   6.0  31.0  32.0   1.0